export const ADMIN_ROUTE = '/dashboard'
export const CHAT_ROUTE = '/chat'
export const CHAT_ROUTE2 = '/chat2'
export const MESSENGER_ROUTE = '/messenger'
export const NOTIF_ROUTE = '/notifications'
export const MESS_BOT_ROUTE = '/messagesbot'
export const REPORTS_ROUTE = '/reports'
export const DISTRIBUTION_ROUTE = '/distribution'
export const DISTRIBUTIONADD_ROUTE = '/distribution_add'
export const SETTINGS_ROUTE = '/settings'

export const THEME_ROUTE = '/theme'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/register'